name: 機能追加
about: 目黒会Botの新規機能の詳細案
title: "[新規機能案]"
labels: ''
assignees: Narangelife

body: 
- type: markdown
  attributes:
    value: |
      ## バグの報告をしていただきありがとうございます。
      以下の質問に答えていただくと、解決しやすくなります。
      赤い印がついているものは必ず答えてください。
